title: Nicolas Gomes # your name (or website title) here
logo: "/images/nicolas.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sou um estudante de TI com experiência em análise de dados, utilizando ferramentas como Power BI e SQL Server para coletar, analisar e visualizar dados complexos de várias fontes. Também sou proficientes em desenvolvimento de aplicações em Python com algumas bibliotecas e DAX, criando soluções personalizadas que atendem às necessidades específicas dos clientes. Minhas habilidades em análise de dados e linguagens de programação permitem-me tomar melhores decisões e melhorar a eficiência dos processos de negócios.
  <a href="https://www.linkedin.com/in/nicolas-gomes-23747a224/">Meu Linkedn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
